import pytest
import json
from pathlib import Path
import sys

root_dir = Path(__file__).resolve().parents[1]
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))
if str(root_dir / "engine" / "src") not in sys.path:
    sys.path.insert(0, str(root_dir / "engine" / "src"))

from bioflow.runtime.command_runner import DryRunCommandRunner
from nodes.class_1 import (
    ProDyDynamicsNode,
    RDKitCheminformaticsNode,
)
from nodes.class_2 import (
    AutoDockVinaDockingNode,
    ColabFoldAlphaFoldNode,
    DiffDockPredictNode,
    ESMFoldNode,
    FPocketNode,
    GNINADockingNode,
    MDAnalysisNode,
    MDTrajNode,
    OpenBabelConvertNode,
    OpenFoldNode,
    OpenMMSimulationNode,
    P2RankPocketNode,
    PlumedNode,
    PmxFEPNode,
    SminaDockingNode,
    TorchDrugNode,
)

SAMPLE_PDB = """ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00 85.00           N
ATOM      2  CA  ALA A   1       1.458   0.000   0.000  1.00 86.50           C
ATOM      3  C   ALA A   1       2.009   1.361   0.000  1.00 87.00           C
ATOM      4  O   ALA A   1       1.272   2.348   0.000  1.00 84.00           O
ATOM      5  CB  ALA A   1       1.986  -0.756  -1.218  1.00 88.00           C
ATOM      6  N   GLY A   2       3.328   1.411   0.000  1.00 90.00           N
ATOM      7  CA  GLY A   2       3.966   2.715   0.000  1.00 92.00           C
ATOM      8  C   GLY A   2       5.474   2.645   0.000  1.00 91.00           C
ATOM      9  O   GLY A   2       6.104   3.705   0.000  1.00 89.00           O
ATOM     10  N   SER A   3       6.052   1.450   0.000  1.00 88.00           N
ATOM     11  CA  SER A   3       7.502   1.284   0.000  1.00 89.00           C
ATOM     12  C   SER A   3       8.196   2.637   0.000  1.00 87.00           C
ATOM     13  O   SER A   3       9.423   2.695   0.000  1.00 86.00           O
END
"""

SAMPLE_PDBQT = """MODEL 1
REMARK VINA RESULT:    -8.400      0.000      0.000
ATOM      1  C   LIG     1       0.000   0.000   0.000  0.00  0.00    +0.000 C
ATOM      2  C   LIG     1       1.400   0.000   0.000  0.00  0.00    +0.000 C
ENDMDL
"""

SAMPLE_SDF = """ligand
  Generated by Test

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
M  END
> <CNNaffinity>
8.4200

> <minimizedAffinity>
-8.4200

$$$$
"""


@pytest.fixture
def test_env(tmp_path):
    fixtures_dir = tmp_path / "fixtures"
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    out_dir = tmp_path / "out"
    out_dir.mkdir(parents=True, exist_ok=True)

    pdb_file = fixtures_dir / "protein.pdb"
    pdb_file.write_text(SAMPLE_PDB, encoding="utf-8")

    pdbqt_file = fixtures_dir / "receptor.pdbqt"
    pdbqt_file.write_text(SAMPLE_PDBQT, encoding="utf-8")

    ligand_pdbqt = fixtures_dir / "ligand.pdbqt"
    ligand_pdbqt.write_text(SAMPLE_PDBQT, encoding="utf-8")

    sdf_file = fixtures_dir / "ligand.sdf"
    sdf_file.write_text(SAMPLE_SDF, encoding="utf-8")

    fa_file = fixtures_dir / "protein.fasta"
    fa_file.write_text(">test_protein\nMKWVTFISLLFLFSSAYSRGVFRR\n", encoding="utf-8")

    csv_file = fixtures_dir / "compounds.csv"
    csv_file.write_text("compound_id,smiles\nC1,CC(=O)Oc1ccccc1C(=O)O\nC2,CC(=O)Nc1ccc(O)cc1\n", encoding="utf-8")

    plumed_file = fixtures_dir / "plumed.dat"
    plumed_file.write_text("d1: DISTANCE ATOMS=1,2\nPRINT ARG=d1 FILE=COLVAR STRIDE=10\n", encoding="utf-8")

    return {
        "fixtures": fixtures_dir,
        "out": out_dir,
        "pdb": pdb_file,
        "pdbqt": pdbqt_file,
        "ligand_pdbqt": ligand_pdbqt,
        "sdf": sdf_file,
        "fasta": fa_file,
        "csv": csv_file,
        "plumed": plumed_file,
    }


# ==============================================================================
# 1. RDKitCheminformaticsNode
# ==============================================================================

def test_rdkit_cheminformatics_node(test_env):
    node = RDKitCheminformaticsNode()
    # Test acetaminophen: CC(=O)Nc1ccc(O)cc1
    smi, mw, logp, hbd = node.run("CC(=O)Nc1ccc(O)cc1")
    assert smi == "CC(=O)Nc1ccc(O)cc1"
    assert round(mw, 1) == 151.1
    assert round(logp, 2) == 1.35
    assert hbd == 2

    # Test aspirin: CC(=O)Oc1ccccc1C(=O)O
    smi, mw, logp, hbd = node.run("CC(=O)Oc1ccccc1C(=O)O")
    assert "C(=O)O" in smi
    assert round(mw, 1) == 180.0
    assert hbd == 1

    # Test file not found error
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/file.smi")

    # Test invalid SMILES error
    with pytest.raises(ValueError):
        node.run("INVALID_SMILES_NOT_A_MOL%%%")


# ==============================================================================
# 2. ProDyDynamicsNode
# ==============================================================================

def test_prody_dynamics_node(test_env):
    node = ProDyDynamicsNode()
    # Missing file check
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/missing.pdb")

    # ANM Model
    res_json, num_modes = node.run(str(test_env["pdb"]), model_type="ANM", num_modes=3)
    assert num_modes == 3
    data = json.loads(res_json)
    assert data["model"] == "ANM"
    assert data["num_atoms"] == 3  # 3 CA atoms in sample pdb
    assert len(data["eigenvalues"]) == 3
    assert all(ev > 0 for ev in data["eigenvalues"])

    # GNM Model
    res_json_gnm, num_modes_gnm = node.run(str(test_env["pdb"]), model_type="GNM", num_modes=2)
    assert num_modes_gnm == 2
    data_gnm = json.loads(res_json_gnm)
    assert data_gnm["model"] == "GNM"
    assert len(data_gnm["eigenvalues"]) == 2


# ==============================================================================
# 3. MDTrajNode & MDAnalysisNode
# ==============================================================================

def test_mdtraj_node(test_env):
    node = MDTrajNode()
    # Missing file check
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/top.pdb", str(test_env["pdb"]))
    with pytest.raises(FileNotFoundError):
        node.run(str(test_env["pdb"]), "/nonexistent/traj.dcd")

    runner = DryRunCommandRunner()
    out_csv = test_env["out"] / "sasa.csv"
    res_csv, mean_sasa = node.run(str(test_env["pdb"]), str(test_env["pdb"]), output_csv=str(out_csv), runner=runner)
    assert Path(res_csv).exists()
    assert mean_sasa > 0.0  # Real calculated SASA
    assert round(mean_sasa, 2) == 3.65
    content = Path(res_csv).read_text(encoding="utf-8")
    assert "frame,total_sasa_nm2" in content

    # Verify manifest export
    assert (test_env["out"] / "run_manifest.sh").exists()
    assert (test_env["out"] / "run_manifest.json").exists()


def test_mdanalysis_node(test_env):
    node = MDAnalysisNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/top.pdb", str(test_env["pdb"]))

    runner = DryRunCommandRunner()
    out_csv = test_env["out"] / "rmsd.csv"
    res_csv, mean_rmsd = node.run(str(test_env["pdb"]), str(test_env["pdb"]), output_csv=str(out_csv), runner=runner)
    assert Path(res_csv).exists()
    assert mean_rmsd >= 0.0
    content = Path(res_csv).read_text(encoding="utf-8")
    assert "frame,rmsd_nm" in content


# ==============================================================================
# 4. ColabFoldAlphaFoldNode & ESMFoldNode
# ==============================================================================

def test_colabfold_alphafold_node(test_env):
    node = ColabFoldAlphaFoldNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/target.fa")

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "colabfold"
    pdb_path, pae_path, mean_plddt = node.run(str(test_env["fasta"]), output_dir=str(out_dir), runner=runner)

    assert Path(pdb_path).exists()
    assert Path(pae_path).exists()
    assert mean_plddt > 0.0  # Real parsed pLDDT from PDB B-factors
    assert (out_dir / "run_manifest.sh").exists()
    assert (out_dir / "run_manifest.json").exists()


def test_esmfold_node(test_env):
    node = ESMFoldNode()
    runner = DryRunCommandRunner()
    out_pdb = test_env["out"] / "esmfold" / "structure.pdb"
    res_pdb, mean_plddt = node.run("MKWVTFISLLFLFSSAYSRGVFRR", output_pdb=str(out_pdb), runner=runner)

    assert Path(res_pdb).exists()
    assert mean_plddt > 0.0
    assert (test_env["out"] / "esmfold" / "run_manifest.sh").exists()


# ==============================================================================
# 5. GNINADockingNode, AutoDockVinaDockingNode, SminaDockingNode
# ==============================================================================

def test_gnina_docking_node(test_env):
    node = GNINADockingNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/rec.pdb", str(test_env["sdf"]))
    with pytest.raises(FileNotFoundError):
        node.run(str(test_env["pdb"]), "/nonexistent/lig.sdf")

    runner = DryRunCommandRunner()
    out_sdf = test_env["out"] / "gnina" / "scored.sdf"
    res_sdf, affinity = node.run(str(test_env["pdb"]), str(test_env["sdf"]), output_sdf=str(out_sdf), runner=runner)
    assert Path(res_sdf).exists()
    assert affinity > 0.0
    assert (test_env["out"] / "gnina" / "run_manifest.sh").exists()


def test_autodock_vina_docking_node(test_env):
    node = AutoDockVinaDockingNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/rec.pdbqt", str(test_env["ligand_pdbqt"]), 10.0, 10.0, 10.0, str(test_env["out"]))

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "vina"
    poses, affinity_tsv = node.run(
        str(test_env["pdbqt"]),
        str(test_env["ligand_pdbqt"]),
        center_x=12.5,
        center_y=24.0,
        center_z=18.2,
        output_dir=str(out_dir),
        runner=runner,
    )
    assert Path(poses).exists()
    assert Path(affinity_tsv).exists()
    tsv_text = Path(affinity_tsv).read_text(encoding="utf-8")
    assert "mode\taffinity_kcal_mol" in tsv_text
    assert (out_dir / "run_manifest.sh").exists()


def test_smina_docking_node(test_env):
    node = SminaDockingNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/rec.pdbqt", str(test_env["sdf"]), str(test_env["out"] / "poses.sdf"))

    runner = DryRunCommandRunner()
    out_sdf = test_env["out"] / "smina" / "poses.sdf"
    (res_sdf,) = node.run(str(test_env["pdbqt"]), str(test_env["sdf"]), output_sdf=str(out_sdf), runner=runner)
    assert Path(res_sdf).exists()
    assert (test_env["out"] / "smina" / "run_manifest.sh").exists()


# ==============================================================================
# 6. Additional CADD Nodes (Simulation, Pockets, FEP, Embeddings, Convert)
# ==============================================================================

def test_openmm_simulation_node(test_env):
    node = OpenMMSimulationNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/solvated.pdb")

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "openmm"
    dcd, csv_out = node.run(str(test_env["pdb"]), simulation_steps=1000, output_dir=str(out_dir), runner=runner)
    assert Path(dcd).exists()
    assert Path(csv_out).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_torchdrug_node(test_env):
    node = TorchDrugNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/library.csv")

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "torchdrug"
    summary_json, emb_path = node.run(str(test_env["csv"]), property_target="BBBP", output_dir=str(out_dir), runner=runner)
    assert Path(emb_path).exists()
    data = json.loads(summary_json)
    assert data["target"] == "BBBP"
    assert data["num_compounds"] == 2
    assert (out_dir / "run_manifest.sh").exists()


def test_openfold_node(test_env):
    node = OpenFoldNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/protein.fa")

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "openfold"
    pdb, attn = node.run(str(test_env["fasta"]), output_dir=str(out_dir), runner=runner)
    assert Path(pdb).exists()
    assert Path(attn).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_diffdock_predict_node(test_env):
    node = DiffDockPredictNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/rec.pdb", "CC(=O)O")

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "diffdock"
    sdf, conf = node.run(str(test_env["pdb"]), "CC(=O)Oc1ccccc1C(=O)O", output_dir=str(out_dir), runner=runner)
    assert Path(sdf).exists()
    assert conf > 0.0
    assert (out_dir / "run_manifest.sh").exists()


def test_p2rank_pocket_node(test_env):
    node = P2RankPocketNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/protein.pdb", str(test_env["out"]))

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "p2rank"
    csv_out, pdb_out = node.run(str(test_env["pdb"]), output_dir=str(out_dir), runner=runner)
    assert Path(csv_out).exists()
    assert Path(pdb_out).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_fpocket_node(test_env):
    node = FPocketNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/protein.pdb", str(test_env["out"]))

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "fpocket"
    info, pockets_dir = node.run(str(test_env["pdb"]), output_dir=str(out_dir), runner=runner)
    assert Path(info).exists()
    assert Path(pockets_dir).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_plumed_node(test_env):
    node = PlumedNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/plumed.dat", str(test_env["pdb"]), str(test_env["out"]))

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "plumed"
    colvar, fes = node.run(str(test_env["plumed"]), str(test_env["pdb"]), output_dir=str(out_dir), runner=runner)
    assert Path(colvar).exists()
    assert Path(fes).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_pmx_fep_node(test_env):
    node = PmxFEPNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/wt.pdb", "A123V", str(test_env["out"]))

    runner = DryRunCommandRunner()
    out_dir = test_env["out"] / "pmx"
    top, pdb = node.run(str(test_env["pdb"]), mutation="A123V", output_dir=str(out_dir), runner=runner)
    assert Path(top).exists()
    assert Path(pdb).exists()
    assert (out_dir / "run_manifest.sh").exists()


def test_openbabel_convert_node(test_env):
    node = OpenBabelConvertNode()
    with pytest.raises(FileNotFoundError):
        node.run("/nonexistent/in.smi", str(test_env["out"] / "out.pdbqt"))

    runner = DryRunCommandRunner()
    smi_file = test_env["fixtures"] / "ligand.smi"
    smi_file.write_text("CC(=O)Oc1ccccc1C(=O)O\n", encoding="utf-8")

    out_file = test_env["out"] / "converted.pdbqt"
    (res_file,) = node.run(str(smi_file), output_file=str(out_file), gen3d=True, runner=runner)
    assert Path(res_file).exists()
    assert (test_env["out"] / "run_manifest.sh").exists()
