import importlib
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

from .ref_nodes import (
    ComfyBIOReportNode,
    DESeq2AnalysisNode,
    DESeq2VisualizationNode,
    FastpQCNode,
    FastpTrimNode,
    FastQCNode,
    ScRNAReportNode,
    ScRNAVisualizationNode,
    SalmonIndexNode,
    SalmonQuantNode,
    SampleMetadataValidatorNode,
    ScanpyClusterNode,
    ScanpyMarkerGenesNode,
    ScanpyNormalizeNode,
    ScanpyQCNode,
    TenxCountNode,
    TrimmomaticTrimNode,
    TximportNode,
)
from .variant_nodes import (
    BcftoolsCallNode,
    BcftoolsFilterNode,
    BwaMem2AlignNode,
    BwaMem2IndexNode,
    MarkDuplicatesNode,
    VariantInputValidatorNode,
    VariantReportNode,
    VariantVisualizationNode,
)
from .atac_nodes import (
    AtacBwaMem2AlignNode,
    AtacBwaMem2IndexNode,
    AtacFastpTrimNode,
    AtacInputValidatorNode,
    AtacMarkDuplicatesNode,
    AtacPeakVisualizationNode,
    AtacQualityFilterNode,
    AtacReportNode,
    Macs3PeakCallingNode,
)
from .metagenome_nodes import (
    BrackenAbundanceNode,
    Kraken2ClassifyNode,
    MetagenomeFastpTrimNode,
    MetagenomeInputValidatorNode,
    MetagenomeReportNode,
    MetagenomeVisualizationNode,
)
from .assembly_nodes import (
    AssemblyFastpTrimNode,
    AssemblyInputValidatorNode,
    AssemblyReportNode,
    AssemblyVisualizationNode,
    QuastQcNode,
    SpadesAssembleNode,
)
from .publication_visualizer_nodes import (
    VolcanoPlotVisualizerNode,
    ManhattanPlotVisualizerNode,
    UmapScatterVisualizerNode,
    ClustermapHeatmapVisualizerNode,
    GseaEnrichmentPlotVisualizerNode,
    OncoPrintVisualizerNode,
    QqPlotVisualizerNode,
    SankeyCellFateVisualizerNode,
    MicrobiomeStackedBarVisualizerNode,
    PcoaScatterVisualizerNode,
    SyntenyGenomeVisualizerNode,
    ChipAtacCoverageProfileVisualizerNode,
    MaPlotVisualizerNode,
    SpatialTissueOverlayVisualizerNode,
    MdTrajectoryPlotterVisualizerNode,
    RamachandranPlotVisualizerNode,
    ProteinLigandInteractionVisualizerNode,
    PhylogeneticTreeVisualizerNode,
    LinkageDisequilibriumVisualizerNode,
    KaplanMeierSurvivalVisualizerNode,
)
from .biopython_nodes import (
    BiopythonSeqIONode,
    BiopythonSeqTranscribeNode,
    BiopythonAlignIONode,
    BiopythonBlastNode,
    BiopythonEntrezNode,
    BiopythonBioPDBNode,
    BiopythonRestrictionNode,
    BiopythonBioMotifsNode,
    LogomakerVisualizerNode,
    BiopythonProtParamNode,
    BiotiteStructureAlignNode,
    SquiggleWaveformNode,
    PyhmmerSearchNode,
    DnaFeaturesViewerNode,
    Primer3DesignNode,
    BioSeqAnalysisNode,
    PyfaidxIndexNode,
    PyCircosPlotNode,
    BiopythonPhyloNode,
    EdlibAlignNode,
    CodonWAnalysisNode,
    PyTFBSScanNode,
    BioKEGGPathwayNode,
    HelicalWheelNode,
    SeqLogoGeneratorNode,
)
from .biopython_sequence_info import BiopythonSequenceInfoNode
from .genomics_longread_nodes import (
    PysamAnalysisNode,
    Cyvcf2VariantNode,
    PybedtoolsIntervalNode,
    MappyAlignNode,
    PyfastxIndexNode,
    SeqKitToolNode,
    Bowtie2AlignNode,
    MosdepthCoverageNode,
    Sniffles2SvNode,
    CuteSvNode,
    FlyeAssembleNode,
    HifiasmAssembleNode,
    RaconPolishNode,
    MedakaConsensusNode,
    DeepVariantCallNode,
)
from .transcriptomics_spatial_nodes import (
    AnnDataIOInMemoryNode,
    ScviToolsLatentNode,
    ScanviCellTypeNode,
    ScVeloDynamicsNode,
    CellRankFateNode,
    SquidpySpatialNode,
    TangramSpatialMappingNode,
    Cell2locationAbundanceNode,
    PyScenicRegulonNode,
    CellPhoneDbInteractionNode,
    GseapyEnrichmentNode,
    MuonMultimodalNode,
    KallistoQuantNode,
    AlevinFryQuantNode,
    StarSoloQuantNode,
    StringTie2AssembleNode,
    FlairIsoformNode,
    IsoToolsSplicingNode,
    CiteSeqCountNode,
    EdgeRAnalysisNode,
    LimmaVoomAnalysisNode,
)
from .epigenomics_nodes import (
    DeepToolsProfileNode,
    TobiasFootprintNode,
    PyGenrichNode,
    Crispresso2ScreenNode,
    MageckScreenNode,
    ScikitFusionNode,
    SeacrPeakNode,
    HomerMotifNode,
    MemeSuiteNode,
    MethyldackelNode,
    CoolerMatrixNode,
    CooltoolsTadNode,
    ChromosightLoopNode,
)
from .proteomics_metabolomics_nodes import (
    PyteomicsMSNode,
    PyOpenMSFeatureNode,
    MatchmsSpectrumNode,
    Spec2VecEmbeddingNode,
    MassqlQueryNode,
    MsDeisotopeNode,
    DiaNNQuantNode,
    MsfraggerSearchNode,
    MsconvertConvertNode,
    MsDialLipidNode,
    SiriusStructureNode,
    MaxQuantQuantNode,
    PerseusCliNode,
    MetaboAnalystRNode,
    MhcquantNeoantigenNode,
)
from .cadd_structural_nodes import (
    ColabFoldAlphaFoldNode,
    ESMFoldNode,
    DiffDockPredictNode,
    GNINADockingNode,
    RDKitCheminformaticsNode,
    OpenMMSimulationNode,
    MDAnalysisNode,
    MDTrajNode,
    TorchDrugNode,
    OpenFoldNode,
    ProDyDynamicsNode,
    AutoDockVinaDockingNode,
    P2RankPocketNode,
    FPocketNode,
    PlumedNode,
    PmxFEPNode,
    OpenBabelConvertNode,
    SminaDockingNode,
)
from .microbiome_nodes import (
    ScikitBioDiversityNode,
    BiomFormatNode,
    Ete3TreeParserNode,
    FastUniFracDistanceNode,
    Dada2AmpliconNode,
    Humann3PathwayNode,
    Metaphlan4ProfileNode,
    GeNomadViromeNode,
    VirSorter2Node,
    CheckVQualityNode,
    ProkkaAnnotationNode,
    BaktaAnnotationNode,
    AmrFinderPlusNode,
    NextstrainAugurNode,
)


NODE_CLASS_MAPPINGS = {
    # Reference / Core Nodes
    "SampleMetadataValidatorNode": SampleMetadataValidatorNode,
    "FastpQCNode": FastpQCNode,
    "FastpTrimNode": FastpTrimNode,
    "FastQCNode": FastQCNode,
    "TenxCountNode": TenxCountNode,
    "ScanpyQCNode": ScanpyQCNode,
    "ScanpyNormalizeNode": ScanpyNormalizeNode,
    "ScanpyClusterNode": ScanpyClusterNode,
    "ScanpyMarkerGenesNode": ScanpyMarkerGenesNode,
    "ScRNAVisualizationNode": ScRNAVisualizationNode,
    "ScRNAReportNode": ScRNAReportNode,
    "SalmonIndexNode": SalmonIndexNode,
    "SalmonQuantNode": SalmonQuantNode,
    "TrimmomaticTrimNode": TrimmomaticTrimNode,
    "TximportNode": TximportNode,
    "DESeq2AnalysisNode": DESeq2AnalysisNode,
    "DESeq2VisualizationNode": DESeq2VisualizationNode,
    "ComfyBIOReportNode": ComfyBIOReportNode,
    "VariantInputValidatorNode": VariantInputValidatorNode,
    "BwaMem2IndexNode": BwaMem2IndexNode,
    "BwaMem2AlignNode": BwaMem2AlignNode,
    "MarkDuplicatesNode": MarkDuplicatesNode,
    "BcftoolsCallNode": BcftoolsCallNode,
    "BcftoolsFilterNode": BcftoolsFilterNode,
    "VariantVisualizationNode": VariantVisualizationNode,
    "VariantReportNode": VariantReportNode,
    "AtacInputValidatorNode": AtacInputValidatorNode,
    "AtacFastpTrimNode": AtacFastpTrimNode,
    "AtacBwaMem2IndexNode": AtacBwaMem2IndexNode,
    "AtacBwaMem2AlignNode": AtacBwaMem2AlignNode,
    "AtacMarkDuplicatesNode": AtacMarkDuplicatesNode,
    "AtacQualityFilterNode": AtacQualityFilterNode,
    "Macs3PeakCallingNode": Macs3PeakCallingNode,
    "AtacPeakVisualizationNode": AtacPeakVisualizationNode,
    "AtacReportNode": AtacReportNode,
    "MetagenomeInputValidatorNode": MetagenomeInputValidatorNode,
    "MetagenomeFastpTrimNode": MetagenomeFastpTrimNode,
    "Kraken2ClassifyNode": Kraken2ClassifyNode,
    "BrackenAbundanceNode": BrackenAbundanceNode,
    "MetagenomeVisualizationNode": MetagenomeVisualizationNode,
    "MetagenomeReportNode": MetagenomeReportNode,
    "AssemblyInputValidatorNode": AssemblyInputValidatorNode,
    "AssemblyFastpTrimNode": AssemblyFastpTrimNode,
    "SpadesAssembleNode": SpadesAssembleNode,
    "QuastQcNode": QuastQcNode,
    "AssemblyVisualizationNode": AssemblyVisualizationNode,
    "AssemblyReportNode": AssemblyReportNode,

    # Publication Visualizer Nodes (20 tools)
    "VolcanoPlotVisualizerNode": VolcanoPlotVisualizerNode,
    "ManhattanPlotVisualizerNode": ManhattanPlotVisualizerNode,
    "UmapScatterVisualizerNode": UmapScatterVisualizerNode,
    "ClustermapHeatmapVisualizerNode": ClustermapHeatmapVisualizerNode,
    "GseaEnrichmentPlotVisualizerNode": GseaEnrichmentPlotVisualizerNode,
    "OncoPrintVisualizerNode": OncoPrintVisualizerNode,
    "QqPlotVisualizerNode": QqPlotVisualizerNode,
    "SankeyCellFateVisualizerNode": SankeyCellFateVisualizerNode,
    "MicrobiomeStackedBarVisualizerNode": MicrobiomeStackedBarVisualizerNode,
    "PcoaScatterVisualizerNode": PcoaScatterVisualizerNode,
    "SyntenyGenomeVisualizerNode": SyntenyGenomeVisualizerNode,
    "ChipAtacCoverageProfileVisualizerNode": ChipAtacCoverageProfileVisualizerNode,
    "MaPlotVisualizerNode": MaPlotVisualizerNode,
    "SpatialTissueOverlayVisualizerNode": SpatialTissueOverlayVisualizerNode,
    "MdTrajectoryPlotterVisualizerNode": MdTrajectoryPlotterVisualizerNode,
    "RamachandranPlotVisualizerNode": RamachandranPlotVisualizerNode,
    "ProteinLigandInteractionVisualizerNode": ProteinLigandInteractionVisualizerNode,
    "PhylogeneticTreeVisualizerNode": PhylogeneticTreeVisualizerNode,
    "LinkageDisequilibriumVisualizerNode": LinkageDisequilibriumVisualizerNode,
    "KaplanMeierSurvivalVisualizerNode": KaplanMeierSurvivalVisualizerNode,

    # Biopython & Sequence Operations Nodes (25 tools)
    "BiopythonSeqIONode": BiopythonSeqIONode,
    "BiopythonSeqTranscribeNode": BiopythonSeqTranscribeNode,
    "BiopythonAlignIONode": BiopythonAlignIONode,
    "BiopythonBlastNode": BiopythonBlastNode,
    "BiopythonEntrezNode": BiopythonEntrezNode,
    "BiopythonBioPDBNode": BiopythonBioPDBNode,
    "BiopythonRestrictionNode": BiopythonRestrictionNode,
    "BiopythonBioMotifsNode": BiopythonBioMotifsNode,
    "LogomakerVisualizerNode": LogomakerVisualizerNode,
    "BiopythonProtParamNode": BiopythonProtParamNode,
    "BiotiteStructureAlignNode": BiotiteStructureAlignNode,
    "SquiggleWaveformNode": SquiggleWaveformNode,
    "PyhmmerSearchNode": PyhmmerSearchNode,
    "DnaFeaturesViewerNode": DnaFeaturesViewerNode,
    "Primer3DesignNode": Primer3DesignNode,
    "BioSeqAnalysisNode": BioSeqAnalysisNode,
    "PyfaidxIndexNode": PyfaidxIndexNode,
    "PyCircosPlotNode": PyCircosPlotNode,
    "BiopythonPhyloNode": BiopythonPhyloNode,
    "EdlibAlignNode": EdlibAlignNode,
    "CodonWAnalysisNode": CodonWAnalysisNode,
    "PyTFBSScanNode": PyTFBSScanNode,
    "BioKEGGPathwayNode": BioKEGGPathwayNode,
    "HelicalWheelNode": HelicalWheelNode,
    "SeqLogoGeneratorNode": SeqLogoGeneratorNode,
    "BiopythonSequenceInfoNode": BiopythonSequenceInfoNode,

    # Genomics & Long-Read Nodes (18 tools)
    "PysamAnalysisNode": PysamAnalysisNode,
    "Cyvcf2VariantNode": Cyvcf2VariantNode,
    "PybedtoolsIntervalNode": PybedtoolsIntervalNode,
    "MappyAlignNode": MappyAlignNode,
    "PyfastxIndexNode": PyfastxIndexNode,
    "SeqKitToolNode": SeqKitToolNode,
    "Bowtie2AlignNode": Bowtie2AlignNode,
    "MosdepthCoverageNode": MosdepthCoverageNode,
    "Sniffles2SvNode": Sniffles2SvNode,
    "CuteSvNode": CuteSvNode,
    "FlyeAssembleNode": FlyeAssembleNode,
    "HifiasmAssembleNode": HifiasmAssembleNode,
    "RaconPolishNode": RaconPolishNode,
    "MedakaConsensusNode": MedakaConsensusNode,
    "DeepVariantCallNode": DeepVariantCallNode,

    # Transcriptomics, Single-Cell & Spatial Nodes (24 tools)
    "AnnDataIOInMemoryNode": AnnDataIOInMemoryNode,
    "ScviToolsLatentNode": ScviToolsLatentNode,
    "ScanviCellTypeNode": ScanviCellTypeNode,
    "ScVeloDynamicsNode": ScVeloDynamicsNode,
    "CellRankFateNode": CellRankFateNode,
    "SquidpySpatialNode": SquidpySpatialNode,
    "TangramSpatialMappingNode": TangramSpatialMappingNode,
    "Cell2locationAbundanceNode": Cell2locationAbundanceNode,
    "PyScenicRegulonNode": PyScenicRegulonNode,
    "CellPhoneDbInteractionNode": CellPhoneDbInteractionNode,
    "GseapyEnrichmentNode": GseapyEnrichmentNode,
    "MuonMultimodalNode": MuonMultimodalNode,
    "KallistoQuantNode": KallistoQuantNode,
    "AlevinFryQuantNode": AlevinFryQuantNode,
    "StarSoloQuantNode": StarSoloQuantNode,
    "StringTie2AssembleNode": StringTie2AssembleNode,
    "FlairIsoformNode": FlairIsoformNode,
    "IsoToolsSplicingNode": IsoToolsSplicingNode,
    "CiteSeqCountNode": CiteSeqCountNode,
    "EdgeRAnalysisNode": EdgeRAnalysisNode,
    "LimmaVoomAnalysisNode": LimmaVoomAnalysisNode,

    # Epigenomics & Functional Screening Nodes (14 tools)
    "DeepToolsProfileNode": DeepToolsProfileNode,
    "TobiasFootprintNode": TobiasFootprintNode,
    "PyGenrichNode": PyGenrichNode,
    "Crispresso2ScreenNode": Crispresso2ScreenNode,
    "MageckScreenNode": MageckScreenNode,
    "ScikitFusionNode": ScikitFusionNode,
    "SeacrPeakNode": SeacrPeakNode,
    "HomerMotifNode": HomerMotifNode,
    "MemeSuiteNode": MemeSuiteNode,
    "MethyldackelNode": MethyldackelNode,
    "CoolerMatrixNode": CoolerMatrixNode,
    "CooltoolsTadNode": CooltoolsTadNode,
    "ChromosightLoopNode": ChromosightLoopNode,

    # Proteomics & Metabolomics Nodes (15 tools)
    "PyteomicsMSNode": PyteomicsMSNode,
    "PyOpenMSFeatureNode": PyOpenMSFeatureNode,
    "MatchmsSpectrumNode": MatchmsSpectrumNode,
    "Spec2VecEmbeddingNode": Spec2VecEmbeddingNode,
    "MassqlQueryNode": MassqlQueryNode,
    "MsDeisotopeNode": MsDeisotopeNode,
    "DiaNNQuantNode": DiaNNQuantNode,
    "MsfraggerSearchNode": MsfraggerSearchNode,
    "MsconvertConvertNode": MsconvertConvertNode,
    "MsDialLipidNode": MsDialLipidNode,
    "SiriusStructureNode": SiriusStructureNode,
    "MaxQuantQuantNode": MaxQuantQuantNode,
    "PerseusCliNode": PerseusCliNode,
    "MetaboAnalystRNode": MetaboAnalystRNode,
    "MhcquantNeoantigenNode": MhcquantNeoantigenNode,

    # Structural Biology & CADD Nodes (18 tools)
    "ColabFoldAlphaFoldNode": ColabFoldAlphaFoldNode,
    "ESMFoldNode": ESMFoldNode,
    "DiffDockPredictNode": DiffDockPredictNode,
    "GNINADockingNode": GNINADockingNode,
    "RDKitCheminformaticsNode": RDKitCheminformaticsNode,
    "OpenMMSimulationNode": OpenMMSimulationNode,
    "MDAnalysisNode": MDAnalysisNode,
    "MDTrajNode": MDTrajNode,
    "TorchDrugNode": TorchDrugNode,
    "OpenFoldNode": OpenFoldNode,
    "ProDyDynamicsNode": ProDyDynamicsNode,
    "AutoDockVinaDockingNode": AutoDockVinaDockingNode,
    "P2RankPocketNode": P2RankPocketNode,
    "FPocketNode": FPocketNode,
    "PlumedNode": PlumedNode,
    "PmxFEPNode": PmxFEPNode,
    "OpenBabelConvertNode": OpenBabelConvertNode,
    "SminaDockingNode": SminaDockingNode,

    # Microbiome, Pathogens & Virome Nodes (16 tools)
    "ScikitBioDiversityNode": ScikitBioDiversityNode,
    "BiomFormatNode": BiomFormatNode,
    "Ete3TreeParserNode": Ete3TreeParserNode,
    "FastUniFracDistanceNode": FastUniFracDistanceNode,
    "Dada2AmpliconNode": Dada2AmpliconNode,
    "Humann3PathwayNode": Humann3PathwayNode,
    "Metaphlan4ProfileNode": Metaphlan4ProfileNode,
    "GeNomadViromeNode": GeNomadViromeNode,
    "VirSorter2Node": VirSorter2Node,
    "CheckVQualityNode": CheckVQualityNode,
    "ProkkaAnnotationNode": ProkkaAnnotationNode,
    "BaktaAnnotationNode": BaktaAnnotationNode,
    "AmrFinderPlusNode": AmrFinderPlusNode,
    "NextstrainAugurNode": NextstrainAugurNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    node_type: node_type.replace("Node", "").replace("Workflow", "Workflow ")
    for node_type in NODE_CLASS_MAPPINGS
}


def resolve_node_class(node_type: str):
    try:
        return NODE_CLASS_MAPPINGS[node_type]
    except KeyError as error:
        raise KeyError(f"No ComfyBIO custom node class registered for {node_type}") from error

