"""Verified standalone command-line nodes."""

from .bcftools import NODE_CLASS_MAPPINGS as BCFTOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BCFTOOLS_NAMES
from .bwa_mem2 import NODE_CLASS_MAPPINGS as BWA_MEM2_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BWA_MEM2_NAMES
from .fastp import NODE_CLASS_MAPPINGS as FASTP_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as FASTP_NAMES
from .fastqc import NODE_CLASS_MAPPINGS as FASTQC_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as FASTQC_NAMES
from .quast import NODE_CLASS_MAPPINGS as QUAST_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as QUAST_NAMES
from .samtools import NODE_CLASS_MAPPINGS as SAMTOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SAMTOOLS_NAMES
from .spades import NODE_CLASS_MAPPINGS as SPADES_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SPADES_NAMES

# RNA-Seq
from .trim_galore import NODE_CLASS_MAPPINGS as TRIM_GALORE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as TRIM_GALORE_NAMES
from .trimmomatic import NODE_CLASS_MAPPINGS as TRIMMOMATIC_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as TRIMMOMATIC_NAMES
from .star import NODE_CLASS_MAPPINGS as STAR_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STAR_NAMES
from .salmon import NODE_CLASS_MAPPINGS as SALMON_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SALMON_NAMES
from .kallisto import NODE_CLASS_MAPPINGS as KALLISTO_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as KALLISTO_NAMES
from .multiqc import NODE_CLASS_MAPPINGS as MULTIQC_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as MULTIQC_NAMES
from .cat_fastq import NODE_CLASS_MAPPINGS as CAT_FASTQ_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CAT_FASTQ_NAMES
from .strandedness import NODE_CLASS_MAPPINGS as STRANDEDNESS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STRANDEDNESS_NAMES
from .umi_tools import NODE_CLASS_MAPPINGS as UMI_TOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as UMI_TOOLS_NAMES
from .picard import NODE_CLASS_MAPPINGS as PICARD_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as PICARD_NAMES
from .sortmerna import NODE_CLASS_MAPPINGS as SORTMERNA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SORTMERNA_NAMES
from .bbtools import NODE_CLASS_MAPPINGS as BBTOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BBTOOLS_NAMES
from .stringtie import NODE_CLASS_MAPPINGS as STRINGTIE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STRINGTIE_NAMES
from .bedtools import NODE_CLASS_MAPPINGS as BEDTOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BEDTOOLS_NAMES
from .ucsc_tools import NODE_CLASS_MAPPINGS as UCSC_TOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as UCSC_TOOLS_NAMES
from .rseqc import NODE_CLASS_MAPPINGS as RSEQC_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as RSEQC_NAMES
from .qualimap import NODE_CLASS_MAPPINGS as QUALIMAP_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as QUALIMAP_NAMES
from .preseq import NODE_CLASS_MAPPINGS as PRESEQ_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as PRESEQ_NAMES
from .dupradar import NODE_CLASS_MAPPINGS as DUPRADAR_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as DUPRADAR_NAMES
from .kraken2 import NODE_CLASS_MAPPINGS as KRAKEN2_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as KRAKEN2_NAMES
from .bracken import NODE_CLASS_MAPPINGS as BRACKEN_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BRACKEN_NAMES
from .sylph import NODE_CLASS_MAPPINGS as SYLPH_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SYLPH_NAMES
from .hisat2 import NODE_CLASS_MAPPINGS as HISAT2_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as HISAT2_NAMES
from .rsem import NODE_CLASS_MAPPINGS as RSEM_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as RSEM_NAMES

# Additional domains
from .bowtie2 import NODE_CLASS_MAPPINGS as BOWTIE2_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BOWTIE2_NAMES
from .flye import NODE_CLASS_MAPPINGS as FLYE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as FLYE_NAMES
from .hifiasm import NODE_CLASS_MAPPINGS as HIFIASM_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as HIFIASM_NAMES
from .mosdepth import NODE_CLASS_MAPPINGS as MOSDEPTH_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as MOSDEPTH_NAMES
from .seqkit import NODE_CLASS_MAPPINGS as SEQKIT_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SEQKIT_NAMES
from .prokka import NODE_CLASS_MAPPINGS as PROKKA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as PROKKA_NAMES
from .bakta import NODE_CLASS_MAPPINGS as BAKTA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as BAKTA_NAMES
from .metaphlan import NODE_CLASS_MAPPINGS as METAPHLAN_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as METAPHLAN_NAMES
from .humann import NODE_CLASS_MAPPINGS as HUMANN_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as HUMANN_NAMES
from .deeptools import NODE_CLASS_MAPPINGS as DEEPTOOLS_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as DEEPTOOLS_NAMES
from .autodock_vina import NODE_CLASS_MAPPINGS as VINA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as VINA_NAMES
from .colabfold import NODE_CLASS_MAPPINGS as COLABFOLD_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as COLABFOLD_NAMES
from .esmfold import NODE_CLASS_MAPPINGS as ESMFOLD_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as ESMFOLD_NAMES

CLASS_2_NODE_MAPPINGS = {
    **FASTP_CLASSES,
    **FASTQC_CLASSES,
    **BWA_MEM2_CLASSES,
    **SAMTOOLS_CLASSES,
    **BCFTOOLS_CLASSES,
    **SPADES_CLASSES,
    **QUAST_CLASSES,
    # RNA-Seq
    **TRIM_GALORE_CLASSES,
    **TRIMMOMATIC_CLASSES,
    **STAR_CLASSES,
    **SALMON_CLASSES,
    **KALLISTO_CLASSES,
    **MULTIQC_CLASSES,
    **CAT_FASTQ_CLASSES,
    **STRANDEDNESS_CLASSES,
    **UMI_TOOLS_CLASSES,
    **PICARD_CLASSES,
    **SORTMERNA_CLASSES,
    **BBTOOLS_CLASSES,
    **STRINGTIE_CLASSES,
    **BEDTOOLS_CLASSES,
    **UCSC_TOOLS_CLASSES,
    **RSEQC_CLASSES,
    **QUALIMAP_CLASSES,
    **PRESEQ_CLASSES,
    **DUPRADAR_CLASSES,
    **KRAKEN2_CLASSES,
    **BRACKEN_CLASSES,
    **SYLPH_CLASSES,
    **HISAT2_CLASSES,
    **RSEM_CLASSES,
    # Additional domains
    **BOWTIE2_CLASSES,
    **FLYE_CLASSES,
    **HIFIASM_CLASSES,
    **MOSDEPTH_CLASSES,
    **SEQKIT_CLASSES,
    **PROKKA_CLASSES,
    **BAKTA_CLASSES,
    **METAPHLAN_CLASSES,
    **HUMANN_CLASSES,
    **DEEPTOOLS_CLASSES,
    **VINA_CLASSES,
    **COLABFOLD_CLASSES,
    **ESMFOLD_CLASSES,
}
CLASS_2_DISPLAY_NAME_MAPPINGS = {
    **FASTP_NAMES,
    **FASTQC_NAMES,
    **BWA_MEM2_NAMES,
    **SAMTOOLS_NAMES,
    **BCFTOOLS_NAMES,
    **SPADES_NAMES,
    **QUAST_NAMES,
    # RNA-Seq
    **TRIM_GALORE_NAMES,
    **TRIMMOMATIC_NAMES,
    **STAR_NAMES,
    **SALMON_NAMES,
    **KALLISTO_NAMES,
    **MULTIQC_NAMES,
    **CAT_FASTQ_NAMES,
    **STRANDEDNESS_NAMES,
    **UMI_TOOLS_NAMES,
    **PICARD_NAMES,
    **SORTMERNA_NAMES,
    **BBTOOLS_NAMES,
    **STRINGTIE_NAMES,
    **BEDTOOLS_NAMES,
    **UCSC_TOOLS_NAMES,
    **RSEQC_NAMES,
    **QUALIMAP_NAMES,
    **PRESEQ_NAMES,
    **DUPRADAR_NAMES,
    **KRAKEN2_NAMES,
    **BRACKEN_NAMES,
    **SYLPH_NAMES,
    **HISAT2_NAMES,
    **RSEM_NAMES,
    # Additional domains
    **BOWTIE2_NAMES,
    **FLYE_NAMES,
    **HIFIASM_NAMES,
    **MOSDEPTH_NAMES,
    **SEQKIT_NAMES,
    **PROKKA_NAMES,
    **BAKTA_NAMES,
    **METAPHLAN_NAMES,
    **HUMANN_NAMES,
    **DEEPTOOLS_NAMES,
    **VINA_NAMES,
    **COLABFOLD_NAMES,
    **ESMFOLD_NAMES,
}

__all__ = ["CLASS_2_NODE_MAPPINGS", "CLASS_2_DISPLAY_NAME_MAPPINGS"]
