"""Verified standalone command-line nodes."""

from .bcftools import NODE_CLASS_MAPPINGS as BCFTOOLS_CLASSES
from .bcftools import NODE_DISPLAY_NAME_MAPPINGS as BCFTOOLS_NAMES
from .bwa_mem2 import NODE_CLASS_MAPPINGS as BWA_MEM2_CLASSES
from .bwa_mem2 import NODE_DISPLAY_NAME_MAPPINGS as BWA_MEM2_NAMES
from .fastp import NODE_CLASS_MAPPINGS as FASTP_CLASSES
from .fastp import NODE_DISPLAY_NAME_MAPPINGS as FASTP_NAMES
from .fastqc import NODE_CLASS_MAPPINGS as FASTQC_CLASSES
from .fastqc import NODE_DISPLAY_NAME_MAPPINGS as FASTQC_NAMES
from .quast import NODE_CLASS_MAPPINGS as QUAST_CLASSES
from .quast import NODE_DISPLAY_NAME_MAPPINGS as QUAST_NAMES
from .samtools import NODE_CLASS_MAPPINGS as SAMTOOLS_CLASSES
from .samtools import NODE_DISPLAY_NAME_MAPPINGS as SAMTOOLS_NAMES
from .spades import NODE_CLASS_MAPPINGS as SPADES_CLASSES
from .spades import NODE_DISPLAY_NAME_MAPPINGS as SPADES_NAMES

CLASS_2_NODE_MAPPINGS = {
    **FASTP_CLASSES,
    **FASTQC_CLASSES,
    **BWA_MEM2_CLASSES,
    **SAMTOOLS_CLASSES,
    **BCFTOOLS_CLASSES,
    **SPADES_CLASSES,
    **QUAST_CLASSES,
}
CLASS_2_DISPLAY_NAME_MAPPINGS = {
    **FASTP_NAMES,
    **FASTQC_NAMES,
    **BWA_MEM2_NAMES,
    **SAMTOOLS_NAMES,
    **BCFTOOLS_NAMES,
    **SPADES_NAMES,
    **QUAST_NAMES,
}

__all__ = ["CLASS_2_NODE_MAPPINGS", "CLASS_2_DISPLAY_NAME_MAPPINGS"]
