"""Verified standalone in-process nodes."""

from .biopython import (
    BiopythonAlignmentStats,
    BiopythonSeqIOStats,
    BiopythonSeqTransform,
    BiopythonGCContent,
    BiopythonPairwiseAlign,
    BiopythonProtParam,
    BiopythonRestrictionDigest,
    BiopythonSeqFilter,
    BiopythonAlignmentStatsNode,
    BiopythonSeqIOStatsNode,
    BiopythonSeqTransformNode,
    BiopythonSeqTranscribeNode,
    BiopythonGCContentNode,
    BiopythonPairwiseAlignNode,
    BiopythonAlignIONode,
    BiopythonProtParamNode,
    BiopythonRestrictionDigestNode,
    BiopythonRestrictionNode,
    BiopythonSeqFilterNode,
    NODE_CLASS_MAPPINGS as BIOPYTHON_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as BIOPYTHON_NAMES,
)
from .tximport import (
    Tximport,
    TximportNode,
    NODE_CLASS_MAPPINGS as TXIMPORT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as TXIMPORT_NAMES,
)
from .rnaseq_pca import (
    DESeq2SampleQC,
    DESeq2SampleQCNode,
    NODE_CLASS_MAPPINGS as RNASEQ_PCA_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as RNASEQ_PCA_NAMES,
)
from .scanpy import (
    ScanpyQC,
    ScanpyNormalize,
    ScanpyCluster,
    ScanpyQCNode,
    ScanpyNormalizeNode,
    ScanpyClusterNode,
    NODE_CLASS_MAPPINGS as SCANPY_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as SCANPY_NAMES,
)
from .anndata import (
    AnnDataInspect,
    AnnDataInspectNode,
    NODE_CLASS_MAPPINGS as ANNDATA_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as ANNDATA_NAMES,
)
from .pysam import (
    PysamStats,
    PysamStatsNode,
    NODE_CLASS_MAPPINGS as PYSAM_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as PYSAM_NAMES,
)
from .cyvcf2 import (
    Cyvcf2Stats,
    Cyvcf2StatsNode,
    NODE_CLASS_MAPPINGS as CYVCF2_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as CYVCF2_NAMES,
)
from .pybedtools import (
    PybedtoolsIntersect,
    PybedtoolsIntersectNode,
    NODE_CLASS_MAPPINGS as PYBEDTOOLS_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as PYBEDTOOLS_NAMES,
)
from .rdkit import (
    RDKitDescriptor,
    RDKitDescriptorNode,
    NODE_CLASS_MAPPINGS as RDKIT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as RDKIT_NAMES,
)
from .plots import (
    VolcanoPlot,
    ManhattanPlot,
    UmapScatter,
    ClustermapHeatmap,
    GseaEnrichmentPlot,
    OncoPrint,
    QqPlot,
    SankeyCellFate,
    MicrobiomeStackedBar,
    PcoaScatter,
    SyntenyGenome,
    ChipAtacCoverageProfile,
    MaPlot,
    SpatialTissueOverlay,
    MdTrajectoryPlotter,
    RamachandranPlot,
    ProteinLigandInteraction,
    PhylogeneticTree,
    LinkageDisequilibrium,
    KaplanMeierSurvival,
    VolcanoPlotNode,
    VolcanoPlotVisualizerNode,
    ManhattanPlotNode,
    ManhattanPlotVisualizerNode,
    UmapScatterNode,
    UmapScatterVisualizerNode,
    ClustermapHeatmapNode,
    ClustermapHeatmapVisualizerNode,
    GseaEnrichmentPlotNode,
    GseaEnrichmentPlotVisualizerNode,
    OncoPrintNode,
    OncoPrintVisualizerNode,
    QqPlotNode,
    QqPlotVisualizerNode,
    SankeyCellFateNode,
    SankeyCellFateVisualizerNode,
    MicrobiomeStackedBarNode,
    MicrobiomeStackedBarVisualizerNode,
    PcoaScatterNode,
    PcoaScatterVisualizerNode,
    SyntenyGenomeNode,
    SyntenyGenomeVisualizerNode,
    ChipAtacCoverageProfileNode,
    ChipAtacCoverageProfileVisualizerNode,
    MaPlotNode,
    MaPlotVisualizerNode,
    SpatialTissueOverlayNode,
    SpatialTissueOverlayVisualizerNode,
    MdTrajectoryPlotterNode,
    MdTrajectoryPlotterVisualizerNode,
    RamachandranPlotNode,
    RamachandranPlotVisualizerNode,
    ProteinLigandInteractionNode,
    ProteinLigandInteractionVisualizerNode,
    PhylogeneticTreeNode,
    PhylogeneticTreeVisualizerNode,
    LinkageDisequilibriumNode,
    LinkageDisequilibriumVisualizerNode,
    KaplanMeierSurvivalNode,
    KaplanMeierSurvivalVisualizerNode,
    PUBLICATION_VISUALIZER_CLASSES,
    NODE_CLASS_MAPPINGS as PLOTS_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as PLOTS_NAMES,
)
from .collect import (
    JoinPaths,
    JoinPathsNode,
    NODE_CLASS_MAPPINGS as COLLECT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as COLLECT_NAMES,
)
from .gseapy import (
    GSEAPathway,
    GSEAPathwayNode,
    NODE_CLASS_MAPPINGS as GSEAPY_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as GSEAPY_NAMES,
)

CLASS_1_NODE_MAPPINGS = {
    **BIOPYTHON_CLASSES,
    **TXIMPORT_CLASSES,
    **RNASEQ_PCA_CLASSES,
    **SCANPY_CLASSES,
    **ANNDATA_CLASSES,
    **PYSAM_CLASSES,
    **CYVCF2_CLASSES,
    **PYBEDTOOLS_CLASSES,
    **RDKIT_CLASSES,
    **PLOTS_CLASSES,
    **GSEAPY_CLASSES,
    **COLLECT_CLASSES,
}
CLASS_1_DISPLAY_NAME_MAPPINGS = {
    **BIOPYTHON_NAMES,
    **TXIMPORT_NAMES,
    **RNASEQ_PCA_NAMES,
    **SCANPY_NAMES,
    **ANNDATA_NAMES,
    **PYSAM_NAMES,
    **CYVCF2_NAMES,
    **PYBEDTOOLS_NAMES,
    **RDKIT_NAMES,
    **PLOTS_NAMES,
    **GSEAPY_NAMES,
    **COLLECT_NAMES,
}

__all__ = [
    "CLASS_1_NODE_MAPPINGS",
    "CLASS_1_DISPLAY_NAME_MAPPINGS",
    "BiopythonAlignmentStats",
    "BiopythonSeqIOStats",
    "BiopythonSeqTransform",
    "BiopythonGCContent",
    "BiopythonPairwiseAlign",
    "BiopythonProtParam",
    "BiopythonRestrictionDigest",
    "BiopythonSeqFilter",
    "BiopythonAlignmentStatsNode",
    "BiopythonSeqIOStatsNode",
    "BiopythonSeqTransformNode",
    "BiopythonSeqTranscribeNode",
    "BiopythonGCContentNode",
    "BiopythonPairwiseAlignNode",
    "BiopythonAlignIONode",
    "BiopythonProtParamNode",
    "BiopythonRestrictionDigestNode",
    "BiopythonRestrictionNode",
    "BiopythonSeqFilterNode",
    "Tximport",
    "TximportNode",
    "DESeq2SampleQC",
    "DESeq2SampleQCNode",
    "ScanpyQC",
    "ScanpyNormalize",
    "ScanpyCluster",
    "ScanpyQCNode",
    "ScanpyNormalizeNode",
    "ScanpyClusterNode",
    "AnnDataInspect",
    "AnnDataInspectNode",
    "PysamStats",
    "PysamStatsNode",
    "Cyvcf2Stats",
    "Cyvcf2StatsNode",
    "PybedtoolsIntersect",
    "PybedtoolsIntersectNode",
    "RDKitDescriptor",
    "RDKitDescriptorNode",
    "VolcanoPlot",
    "VolcanoPlotNode",
    "VolcanoPlotVisualizerNode",
    "ManhattanPlot",
    "ManhattanPlotNode",
    "ManhattanPlotVisualizerNode",
    "UmapScatter",
    "UmapScatterNode",
    "UmapScatterVisualizerNode",
    "ClustermapHeatmap",
    "ClustermapHeatmapNode",
    "ClustermapHeatmapVisualizerNode",
    "GseaEnrichmentPlot",
    "GseaEnrichmentPlotNode",
    "GseaEnrichmentPlotVisualizerNode",
    "OncoPrint",
    "OncoPrintNode",
    "OncoPrintVisualizerNode",
    "QqPlot",
    "QqPlotNode",
    "QqPlotVisualizerNode",
    "SankeyCellFate",
    "SankeyCellFateNode",
    "SankeyCellFateVisualizerNode",
    "MicrobiomeStackedBar",
    "MicrobiomeStackedBarNode",
    "MicrobiomeStackedBarVisualizerNode",
    "PcoaScatter",
    "PcoaScatterNode",
    "PcoaScatterVisualizerNode",
    "SyntenyGenome",
    "SyntenyGenomeNode",
    "SyntenyGenomeVisualizerNode",
    "ChipAtacCoverageProfile",
    "ChipAtacCoverageProfileNode",
    "ChipAtacCoverageProfileVisualizerNode",
    "MaPlot",
    "MaPlotNode",
    "MaPlotVisualizerNode",
    "SpatialTissueOverlay",
    "SpatialTissueOverlayNode",
    "SpatialTissueOverlayVisualizerNode",
    "MdTrajectoryPlotter",
    "MdTrajectoryPlotterNode",
    "MdTrajectoryPlotterVisualizerNode",
    "RamachandranPlot",
    "RamachandranPlotNode",
    "RamachandranPlotVisualizerNode",
    "ProteinLigandInteraction",
    "ProteinLigandInteractionNode",
    "ProteinLigandInteractionVisualizerNode",
    "PhylogeneticTree",
    "PhylogeneticTreeNode",
    "PhylogeneticTreeVisualizerNode",
    "LinkageDisequilibrium",
    "LinkageDisequilibriumNode",
    "LinkageDisequilibriumVisualizerNode",
    "KaplanMeierSurvival",
    "KaplanMeierSurvivalNode",
    "KaplanMeierSurvivalVisualizerNode",
    "PUBLICATION_VISUALIZER_CLASSES",
    "GSEAPathway",
    "GSEAPathwayNode",
    "JoinPaths",
    "JoinPathsNode",
]
